-- SCRIPT DE APAGAR
-- Banco de Dados: MySQL 8.0
-- Base de Dados: magaluDB

-- BASE DE DADOS
USE magaluDB;

-- TABELAS
DROP TABLE IF EXISTS PAGAMENTO;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS SACOLA;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS possui;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS COMPRADOR;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS DEPARTAMENTO;

-- VIEWS
DROP VIEW IF EXISTS ProdutosMaisVendidos;
DROP VIEW IF EXISTS VendasPorDepartamento;
DROP VIEW IF EXISTS MetodoPagamentoMaisPopular;